env: mpe_fluid

render_args:
  srk: [1,2,4]
  sr_color: ["#2CAFAC","#FB5607", "#1982C4"]

twoagent: False
agentnames:
  - agent
n_agents: 8
mac: "basic_mac" # "entity_mac" for REFIL/CAMA

env_args:
  scenario_id: "simple_spread.py"
  scenario_config:
    episode_limit: 100
    max_n_agents : 8
    max_n_landmarks: 8
    
    # train(in-domain)
    num_agents : [1, 3]
    num_landmarks: [1, 3]
    intra_trajectory: [1, 1]

    OOD:      
      # OOD 1
      - num_agents : [5]
        num_landmarks: [5]
        intra_trajectory: [2, 0]
      # OOD 2
      - num_agents : [5]
        num_landmarks: [5]
        intra_trajectory: [0, 2]

    delta_entities: # only keys got meaning
      add_agent: [50, 70] 
      add_landmark: [70]
    
    dropout:
      False